/* Deletes the database if it exists to avoid any errors */
DROP DATABASE IF EXISTS tournament;

/* Create the database tournament */
CREATE DATABASE tournament;

/* Connect to the database */
\c tournament;


/*
Creates the players table which include the name and player_id
of the players. player_id will be generated by the database.

    player_id |      name
    -------------------------------
            1 | Twiglight Sparkle |
            2 | Applejack         |
            3 | Fluttershy        |
            4 | Pinkie Pie        |
*/


CREATE TABLE players (
        player_id serial PRIMARY KEY,
        name varchar (25) NOT NULL
);

/*
Creates results table to hold the match id's and player_id's
that correspond with the winner and loser of the match.

     match_id |  winner | loser
    -----------------------------
            1 |      1  |    2  |
            2 |      3  |    4  |
*/


CREATE TABLE results (
        match_id serial PRIMARY KEY,
        winner integer REFERENCES players(player_id) NOT NULL,
        loser integer REFERENCES players(player_id) NOT NULL
);


/*
Creates a view standings table, that will be sorted by total_wins
and then by total_matches as such:

    player_id |      name         | total_wins | total_matches
    ----------------------------------------------------------
            1 | Twiglight Sparkle |          1 |            1
            2 | Applejack         |          0 |            1
            3 | Fluttershy        |          0 |            1
            4 | Pinkie Pie        |          0 |            1
*/


CREATE VIEW standings AS
SELECT players.player_id, players.name,
(SELECT count(results.winner)
    FROM results
    WHERE players.player_id = results.winner)
    AS total_wins,
(SELECT count(results.match_id)
    FROM results
    WHERE players.player_id = results.winner
    OR players.player_id = results.loser)
    AS total_matches
FROM players
ORDER BY total_wins DESC, total_matches DESC;
